[package]
name = "_json_rs"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
license = "MIT"

[dependencies]
cpython-sys = { path = "../cpython-sys" }

[build-dependencies]
cpython-build-helper = { path = "../cpython-build-helper" }

[lib]
name = "_json_rs"
crate-type = ["cdylib", "rlib"]
