[package]
name = "_gzip_rs"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
cpython-sys = { path = "../cpython-sys" }
libz-rs-sys = { version = "=0.6.7", default-features = false, features = ["std", "rust-allocator"] }

[build-dependencies]
cpython-build-helper = { path = "../cpython-build-helper" }

[lib]
name = "_gzip_rs"
crate-type = ["cdylib", "rlib"]
