[package]
name = "_re_rs"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
cpython-sys = { path = "../cpython-sys" }
regex = "=1.13.1"

[build-dependencies]
cpython-build-helper = { path = "../cpython-build-helper" }

[lib]
name = "_re_rs"
crate-type = ["cdylib", "rlib"]
