[package]
name = "_re_rs"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
cpython-sys = { path = "../cpython-sys" }
regex-syntax = { version = "=0.8.11", default-features = false, features = ["std"] }
regex-automata = { version = "=0.4.18", default-features = false, features = ["std", "syntax", "meta", "nfa-pikevm", "hybrid", "dfa-onepass", "nfa-backtrack", "perf-inline", "perf-literal"] }

[dev-dependencies]
regex = { version = "=1.13.1", default-features = false, features = ["std", "perf"] }

[build-dependencies]
cpython-build-helper = { path = "../cpython-build-helper" }

[lib]
name = "_re_rs"
crate-type = ["cdylib", "rlib"]
