[package]
name = "_fractions_rs"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
license = "PSF-2.0"

[dependencies]
num-bigint = { version = "=0.4.8", default-features = false }
num-integer = { version = "=0.1.47", default-features = false }
num-rational = { version = "=0.4.2", default-features = false, features = ["num-bigint"] }

[build-dependencies]
cpython-build-helper = { path = "../cpython-build-helper" }

[lib]
name = "_fractions_rs"
crate-type = ["cdylib", "rlib"]
