[package]
name = "_pathlib_rs"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
cpython-sys = { path = "../cpython-sys" }
# typed-path 0.12.3 is dual-licensed MIT OR Apache-2.0.
typed-path = { version = "=0.12.3" }

[build-dependencies]
cpython-build-helper = { path = "../cpython-build-helper" }

[lib]
name = "_pathlib_rs"
crate-type = ["cdylib", "rlib"]
