use std::cell::UnsafeCell;
use std::ffi::{c_char, c_int, c_long, c_void};
use std::ptr;

use cpython_sys::{
    METH_FASTCALL, Py_DecRef, PyErr_Occurred, PyErr_SetString, PyExc_TypeError, PyMethodDef,
    PyMethodDefFuncPointer, PyModuleDef, PyModuleDef_HEAD_INIT, PyModuleDef_Init,
    PyModuleDef_Slot, PyObject, Py_NewRef, Py_ssize_t, _Py_NoneStruct,
};

unsafe extern "C" {
    fn PyObject_GetIter(object: *mut PyObject) -> *mut PyObject;
    fn PyIter_Next(iterator: *mut PyObject) -> *mut PyObject;
    fn PyObject_CallFunctionObjArgs(callable: *mut PyObject, ...) -> *mut PyObject;
    fn PyNumber_Subtract(left: *mut PyObject, right: *mut PyObject) -> *mut PyObject;
    fn PyObject_SetItem(
        object: *mut PyObject,
        key: *mut PyObject,
        value: *mut PyObject,
    ) -> std::ffi::c_int;
    fn PyLong_FromLong(value: c_long) -> *mut PyObject;
}

struct Owned(*mut PyObject);

impl Drop for Owned {
    fn drop(&mut self) {
        if !self.0.is_null() {
            unsafe { Py_DecRef(self.0) };
        }
    }
}

unsafe fn subtract_iterable(
    mapping: *mut PyObject,
    iterable: *mut PyObject,
    mapping_get: *mut PyObject,
) -> *mut PyObject {
    let iterator = Owned(unsafe { PyObject_GetIter(iterable) });
    if iterator.0.is_null() {
        return ptr::null_mut();
    }
    let zero = Owned(unsafe { PyLong_FromLong(0) });
    if zero.0.is_null() {
        return ptr::null_mut();
    }
    let one = Owned(unsafe { PyLong_FromLong(1) });
    if one.0.is_null() {
        return ptr::null_mut();
    }

    loop {
        let key = Owned(unsafe { PyIter_Next(iterator.0) });
        if key.0.is_null() {
            if unsafe { PyErr_Occurred() }.is_null() {
                break;
            }
            return ptr::null_mut();
        }

        let current = Owned(unsafe {
            PyObject_CallFunctionObjArgs(
                mapping_get,
                key.0,
                zero.0,
                ptr::null_mut::<PyObject>(),
            )
        });
        if current.0.is_null() {
            return ptr::null_mut();
        }
        let next = Owned(unsafe { PyNumber_Subtract(current.0, one.0) });
        if next.0.is_null() {
            return ptr::null_mut();
        }
        if unsafe { PyObject_SetItem(mapping, key.0, next.0) } < 0 {
            return ptr::null_mut();
        }
    }

    unsafe { Py_NewRef(ptr::addr_of_mut!(_Py_NoneStruct)) }
}

unsafe extern "C" fn subtract_iterable_method(
    _module: *mut PyObject,
    args: *mut *mut PyObject,
    nargs: Py_ssize_t,
) -> *mut PyObject {
    if nargs != 3 {
        unsafe {
            PyErr_SetString(
                PyExc_TypeError,
                c"subtract_iterable requires a mapping, iterable, and bound get method".as_ptr(),
            )
        };
        return ptr::null_mut();
    }

    let (mapping, iterable, mapping_get) = unsafe { (*args, *args.add(1), *args.add(2)) };
    unsafe { subtract_iterable(mapping, iterable, mapping_get) }
}

struct ModuleDef(UnsafeCell<PyModuleDef>);

unsafe impl Sync for ModuleDef {}

struct ModuleSlots([PyModuleDef_Slot; 3]);

unsafe impl Sync for ModuleSlots {}

unsafe extern "C" fn module_exec(_module: *mut PyObject) -> c_int {
    0
}

// Slot IDs are generated by the pinned CPython 3.16 headers. All operation
// state is held by Python objects passed to each call, so interpreters share
// only immutable method and slot definitions.
const PY_MOD_EXEC: c_int = 85;
const PY_MOD_MULTIPLE_INTERPRETERS: c_int = 86;
const PY_MOD_PER_INTERPRETER_GIL_SUPPORTED: *mut c_void = 2 as *mut c_void;

static MODULE_SLOTS: ModuleSlots = ModuleSlots([
    PyModuleDef_Slot {
        slot: PY_MOD_EXEC,
        value: module_exec as *const () as *mut c_void,
    },
    PyModuleDef_Slot {
        slot: PY_MOD_MULTIPLE_INTERPRETERS,
        value: PY_MOD_PER_INTERPRETER_GIL_SUPPORTED,
    },
    PyModuleDef_Slot {
        slot: 0,
        value: ptr::null_mut(),
    },
]);

static METHODS: [PyMethodDef; 2] = [
    PyMethodDef {
        ml_name: c"subtract_iterable".as_ptr() as *mut c_char,
        ml_meth: PyMethodDefFuncPointer {
            PyCFunctionFast: subtract_iterable_method,
        },
        ml_flags: METH_FASTCALL,
        ml_doc: c"Subtract one from the mapped count for each iterable element."
            .as_ptr() as *mut c_char,
    },
    PyMethodDef::zeroed(),
];

static MODULE: ModuleDef = ModuleDef(UnsafeCell::new(PyModuleDef {
    m_base: PyModuleDef_HEAD_INIT,
    m_name: c"_collections_rs".as_ptr() as *mut c_char,
    m_doc: c"Rust counting operations for collections.".as_ptr() as *mut c_char,
    m_size: 0,
    m_methods: METHODS.as_ptr() as *mut PyMethodDef,
    m_slots: MODULE_SLOTS.0.as_ptr() as *mut PyModuleDef_Slot,
    m_traverse: None,
    m_clear: None,
    m_free: None,
}));

#[unsafe(no_mangle)]
pub extern "C" fn PyInit__collections_rs() -> *mut PyObject {
    unsafe { PyModuleDef_Init(MODULE.0.get()) }
}
