[package]
name = "_shlex_rs"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
cpython-sys = { path = "../cpython-sys" }
# Crates.io shlex 1.3.0 is dual-licensed MIT OR Apache-2.0.
shlex = "=1.3.0"

[build-dependencies]
cpython-build-helper = { path = "../cpython-build-helper" }

[lib]
name = "_shlex_rs"
crate-type = ["cdylib", "rlib"]
