"""Product scope exclusions, enforced on the installed tree.

Two exclusions are structural rather than a matter of what happens to get
built, and they need opposite handling:

  GUI (Tcl/Tk, X11)   Tcl/Tk is never acquired and never built, so the
                      `_tkinter` extension is simply absent. The pure-Python
                      `tkinter` package, however, *is* always installed, so it
                      has to be removed as well — an installed-but-unimportable
                      package is worse than an absent one, because a
                      find_spec-style probe reports it as available.
  Packaging           `pip`, `ensurepip` (with its bundled wheel) and `venv`
                      are ordinary parts of the CPython standard library and
                      are installed unconditionally, so they have to be
                      removed deliberately after `make install`.

Both are enforced here rather than by a configure flag because CPython has no
flag for either — and a silent re-addition after a CPython point release is
exactly the kind of drift this module exists to make loud. The regression
suite and generated bytecode caches are kept through validation, then removed
from the consumer distribution immediately before archiving.
"""

from __future__ import annotations

import shutil
from pathlib import Path

# Directory names under lib/pythonX.Y/ that are installed unconditionally and
# must not ship. `ensurepip/_bundled/` carries a full pip wheel, so removing
# only the top-level launcher would leave the installer's bytes in the payload.
EXCLUDED_STDLIB_DIRS = ("ensurepip", "venv", "tkinter", "idlelib")

# `make install` also installs CPython's full regression suite. Keep it in the
# staged tree so packaging can run `python -m test`, then remove it from the
# consumer distribution. Bytecode caches are generated install products, not
# runtime inputs: source modules remain available and Python can compile them
# on demand after relocation.
DISTRIBUTION_EXCLUDED_STDLIB_DIRS = ("test",)

# GUI-only single modules that cannot function without Tk. `turtle` draws
# through tkinter, and `idlelib` is the IDE built on it; shipping either
# leaves a name that imports-then-fails or a launcher that cannot run.
EXCLUDED_STDLIB_FILES = ("turtle.py",)

# Console scripts under bin/ that exist to drive a package installer.
EXCLUDED_SCRIPT_PREFIXES = ("pip", "idle")


class ScopeError(Exception):
    """A scope exclusion could not be enforced."""


def stdlib_directories(install: Path) -> list[Path]:
    """The lib/pythonX.Y directories of an installed tree."""
    return sorted(p for p in Path(install).glob("lib/python3.*") if p.is_dir())


def enforce_exclusions(install: Path) -> dict:
    """Remove the excluded components from an installed tree.

    Returns a report of what was removed. Idempotent: a second call finds
    nothing and reports nothing, which is what makes it safe to run on a
    re-packaged tree.
    """
    install = Path(install)
    libraries = stdlib_directories(install)
    if not libraries:
        raise ScopeError(f"no lib/python3.* directory under {install}")
    removed: list[str] = []
    for library in libraries:
        for name in EXCLUDED_STDLIB_DIRS:
            target = library / name
            if target.is_dir():
                shutil.rmtree(target)
                removed.append(str(target.relative_to(install)))
        for name in EXCLUDED_STDLIB_FILES:
            target = library / name
            if target.is_file():
                target.unlink()
                removed.append(str(target.relative_to(install)))
    binary = install / "bin"
    if binary.is_dir():
        for script in sorted(binary.iterdir()):
            if script.name.startswith(EXCLUDED_SCRIPT_PREFIXES):
                script.unlink()
                removed.append(str(script.relative_to(install)))
    return {"removed": removed, "install": str(install)}


def verify_exclusions(install: Path) -> list[str]:
    """Every excluded component still present, as human-readable findings."""
    install = Path(install)
    found: list[str] = []
    for library in stdlib_directories(install):
        for name in (*EXCLUDED_STDLIB_DIRS, *EXCLUDED_STDLIB_FILES):
            if (library / name).exists():
                found.append(str((library / name).relative_to(install)))
    binary = install / "bin"
    if binary.is_dir():
        for script in sorted(binary.iterdir()):
            if script.name.startswith(EXCLUDED_SCRIPT_PREFIXES):
                found.append(str(script.relative_to(install)))
    return found


def prune_distribution_payload(install: Path) -> dict[str, object]:
    """Remove regression-suite files and generated bytecode from a release tree.

    The CPython test suite remains available through build and package
    validation. This runs only after those checks, immediately before the
    consumer archive is written.
    """
    install = Path(install)
    libraries = stdlib_directories(install)
    if not libraries:
        raise ScopeError(f"no lib/python3.* directory under {install}")

    bytecode_files = sorted(install.rglob("*.pyc"))
    cache_directories = sorted(
        (path for path in install.rglob("__pycache__")
         if path.is_dir() or path.is_symlink()),
        key=lambda path: len(path.parts),
        reverse=True,
    )
    removed_bytecode_files = sum(
        path.is_file() or path.is_symlink() for path in bytecode_files
    )
    removed_stdlib_dirs: list[str] = []
    for library in libraries:
        for name in DISTRIBUTION_EXCLUDED_STDLIB_DIRS:
            target = library / name
            if target.is_dir():
                shutil.rmtree(target)
                removed_stdlib_dirs.append(str(target.relative_to(install)))

    for path in bytecode_files:
        if path.is_file() or path.is_symlink():
            path.unlink()
    removed_cache_directories = len(cache_directories)
    for path in cache_directories:
        if not path.exists() and not path.is_symlink():
            continue
        if path.is_symlink():
            path.unlink()
        else:
            shutil.rmtree(path)

    remaining = verify_distribution_payload(install)
    if remaining:
        raise ScopeError(
            "distribution payload still contains excluded paths: "
            + ", ".join(remaining[:10])
        )
    test_importable = probe_in_process(
        install / "bin" / "python3.14", modules=["test"], write_bytecode=False
    )["test"]
    if test_importable:
        raise ScopeError("CPython regression suite remains importable in distribution")

    return {
        "excluded_stdlib_dirs": list(DISTRIBUTION_EXCLUDED_STDLIB_DIRS),
        "removed_stdlib_dirs": removed_stdlib_dirs,
        "removed_bytecode_files": removed_bytecode_files,
        "removed_bytecode_cache_dirs": removed_cache_directories,
        "remaining_excluded_paths": remaining,
        "test_importable": test_importable,
        "ok": True,
    }


def verify_distribution_payload(install: Path) -> list[str]:
    """Find test-suite files or bytecode caches that could enter the archive."""
    install = Path(install)
    found: list[str] = []
    for library in stdlib_directories(install):
        for name in DISTRIBUTION_EXCLUDED_STDLIB_DIRS:
            target = library / name
            if target.exists():
                found.append(str(target.relative_to(install)))
    found.extend(
        str(path.relative_to(install))
        for path in install.rglob("__pycache__")
    )
    found.extend(
        str(path.relative_to(install))
        for path in install.rglob("*.pyc")
    )
    return sorted(found)


def excluded_module_names() -> list[str]:
    """Importable names the shipped tree must not expose."""
    names = [name for name in EXCLUDED_STDLIB_DIRS]
    names += [Path(name).stem for name in EXCLUDED_STDLIB_FILES]
    # `_tkinter` is the extension; `tkinter` is the package it backs.
    names.append("_tkinter")
    return sorted(set(names))


def probe_in_process(
    python: Path,
    modules: list[str] | None = None,
    *,
    write_bytecode: bool = True,
) -> dict:
    """Ask the built interpreter whether the excluded modules are importable.

    Filesystem absence is necessary but not sufficient — a stray .pyc, a
    zipimport path, or a stale sys.path entry could still make an excluded
    module importable. This checks the actual runtime behaviour, which is what
    the exclusion is about.
    """
    import json
    import subprocess

    names = modules if modules is not None else excluded_module_names()
    code = (
        "import importlib.util as u, json\n"
        f"mods = {names!r}\n"
        "print(json.dumps({m: u.find_spec(m) is not None for m in mods}))\n"
    )
    command = [str(python)]
    if not write_bytecode:
        command.append("-B")
    command += ["-c", code]
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode != 0:
        raise ScopeError(
            f"could not probe {python}: {result.stderr.strip() or result.stdout.strip()}"
        )
    return json.loads(result.stdout.strip().splitlines()[-1])
