[package]
name = "cpython-rust-staticlib"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
_asyncio_rs = { path = "../_asyncio_rs" }
_base64 = { path = "../_base64" }
_bisect_rs = { path = "../_bisect_rs" }
_codecs_rs = { path = "../_codecs_rs" }
_concurrent_futures_rs = { path = "../_concurrent_futures_rs" }
_contextlib_rs = { path = "../_contextlib_rs" }
_heapq_rs = { path = "../_heapq_rs" }
_html_parser_rs = { path = "../_html_parser_rs" }
_itertools_rs = { path = "../_itertools_rs" }
_posixpath_rs = { path = "../_posixpath_rs" }
_random_rs = { path = "../_random_rs", features = ["static-module"] }
_ssl_rs = { path = "../_ssl_rs" }
_tempfile_rs = { path = "../_tempfile_rs" }
_typing_rs = { path = "../_typing_rs" }

[lib]
name = "cpython_rust_staticlib"
crate-type = ["staticlib"]
