[package]
name = "_tarfile_rs"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
license = "PSF-2.0"

[dependencies]
cpython-sys = { path = "../cpython-sys" }
tar = { version = "=0.4.46", default-features = false }

[build-dependencies]
cpython-build-helper = { path = "../cpython-build-helper" }

[lib]
name = "_tarfile_rs"
crate-type = ["cdylib", "rlib"]
