[package]
name = "_base64"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
base64 = { version = "=0.23.1", default-features = false, features = ["std"] } # MIT OR Apache-2.0
data-encoding = { version = "=2.9.0", default-features = false, features = ["alloc"] } # MIT
cpython-sys ={ path = "../cpython-sys" }

[build-dependencies]
cpython-build-helper = { path = "../cpython-build-helper" }

[lib]
name = "_base64"
# For shared builds, we generate a c dynamic library. Static builds use the rlib
crate-type = ["cdylib", "rlib"]
