[package]
name = "_bz2_rs"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
cpython-sys = { path = "../cpython-sys" }
bzip2 = "=0.6.1"

[build-dependencies]
cpython-build-helper = { path = "../cpython-build-helper" }

[lib]
name = "_bz2_rs"
crate-type = ["cdylib", "rlib"]
