[package]
name = "_glob_rs"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
license = "PSF-2.0"

[dependencies]
libc = { version = "=0.2.189", default-features = false } # MIT OR Apache-2.0

[build-dependencies]
cpython-build-helper = { path = "../cpython-build-helper" }

[lib]
name = "_glob_rs"
crate-type = ["cdylib", "rlib"]
