[package]
name = "_configparser_rs"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
configparser = { version = "=3.3.0", features = ["indexmap"] }
cpython-sys = { path = "../cpython-sys" }

[build-dependencies]
cpython-build-helper = { path = "../cpython-build-helper" }

[lib]
name = "_configparser_rs"
crate-type = ["cdylib", "rlib"]
